### ISSUE TITLE
Heroku build assets:precompile - no implicit conversion of nil to string

### ISSUE THREAD

**Issue by chrisdobler** [spark-solutions/spark-starter-kit#32]
I tried uploading to heroku but was unable to complete the build process.

`remote:        cp -rf app/assets/webpack/*.woff* app/assets/webpack/*.svg app/assets/webpack/*.ttf app/assets/webpack/*.eot* app/assets/webpack/*.png public/assets
remote:        rake aborted!
remote:        TypeError: no implicit conversion of nil into String
remote:        /tmp/build_30cba7dd8e51963c7938f301a64f0807/config/environments/production.rb:26:in '+'
remote:        /tmp/build_30cba7dd8e51963c7938f301a64f0807/config/environments/production.rb:26:in 'block in <top (required)>'
remote:        /tmp/build_30cba7dd8e51963c7938f301a64f0807/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/railtie.rb:210:in 'instance_eval'
`

**Comment by chrisdobler** [comment]
I realized I needed to add the environment variables.
