### ISSUE TITLE
ReferenceError: setTimeout is not defined

### ISSUE THREAD

**Issue by jshumakerpruitt** [spark-solutions/spark-starter-kit#68]
I just cloned the repo and ran `bin/setup`. Then I ran `foreman start -f Procfile.dev`.

I get the following error when I navigate to '/':  

```
Rendered spree/home/index.haml within layouts/application (1321.1ms)
Completed 500 Internal Server Error in 1559ms (ActiveRecord: 5.1ms)

ExecJS::ProgramError - ReferenceError: setTimeout is not defined:
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:98:in `wrap_error'
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:15:in `rescue in block in initialize'
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:12:in `block in initialize'
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:73:in `lock'
  execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:9:in `initialize'
  execjs (2.7.0) lib/execjs/runtime.rb:57:in `compile'
  execjs (2.7.0) lib/execjs/module.rb:27:in `compile'
  react-rails (1.8.0) lib/react/server_rendering/exec_js_renderer.rb:10:in `initialize'
  react-rails (1.8.0) lib/react/server_rendering/sprockets_renderer.rb:25:in `initialize'
  react-rails (1.8.0) lib/react/server_rendering.rb:22:in `create_renderer'
  react-rails (1.8.0) lib/react/server_rendering.rb:12:in `block in reset_pool'
  connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:169:in `try_create'
  connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:81:in `block (2 levels) in pop'
  connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:77:in `block in pop'
  connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:76:in `pop'
  connection_pool (2.2.0) lib/connection_pool.rb:89:in `checkout'
  connection_pool (2.2.0) lib/connection_pool.rb:61:in `block in with'
  connection_pool (2.2.0) lib/connection_pool.rb:60:in `with'
  react-rails (1.8.0) lib/react/server_rendering.rb:16:in `render'
  react-rails (1.8.0) lib/react/rails/component_mount.rb:33:in `block in react_component'
  actionview (4.2.7.1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.7.1) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.2.7.1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.2.7.1) lib/action_view/helpers/tag_helper.rb:106:in `content_tag'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:61:in `content_tag_with_haml'
  react-rails (1.8.0) lib/react/rails/component_mount.rb:48:in `react_component'
  react-rails (1.8.0) lib/react/rails/view_helper.rb:21:in `react_component'
  app/views/spree/home/index.haml:1:in `_d4116bc6bb0a33c713909f9027a25be2'
  actionview (4.2.7.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.7.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.7.1) lib/action_view/template.rb:143:in `render'
  deface (1.0.2) lib/deface/action_view_extensions.rb:41:in `render'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.7.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.7.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:46:in `render_template'
  actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:27:in `render'
  actionview (4.2.7.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.7.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.7.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.7.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.7.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/js/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.7.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.7.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  bullet (5.1.1) lib/bullet/rack.rb:10:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.2.7.1) lib/active_record/migration.rb:377:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rollbar (2.12.0) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
  rollbar (2.12.0) lib/rollbar.rb:735:in `scoped'
  rollbar (2.12.0) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  rollbar (2.12.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  web-console (3.3.0) lib/web_console/middleware.rb:131:in `call_app'
  web-console (3.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.3.0) lib/web_console/middleware.rb:18:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_traci  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_traci
ng.rb:96:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/rack/browser_monitoring.rb:32:in `trac
ed_call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_traci
ng.rb:96:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/rack/developer_mode.rb:48:in `traced_c
all'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_traci
ng.rb:96:in `call'
  bullet (5.1.1) lib/bullet/rack.rb:10:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_traci
ng.rb:96:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_traci
ng.rb:96:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_traci
ng.rb:96:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_traci
ng.rb:96:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_traci
ng.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `ca
ll'
  newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_traci
ng.rb:96:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
...
```

**Comment by chrisdobler** [comment]
I had the same issue, it drove me absolutely crazy for a week because I thought it was due to some component I was using that was incompatible with server side scripting, but I was unable to find the culprit after rewinding my project back several times. I ended up just having to disable server side scripting on the root page.

**Comment by krzysiek1507** [comment]
Unfortunately npm doesn't have lockfile so we have Russian roulette with dependencies of dependencies. We would like to move to [yarn](https://github.com/yarnpkg/yarn) as soon as possible but we have to be sure that it's stable.

**Comment by jshumakerpruitt** [comment]
@krzysiek1507 Any idea which npm package is causing this issue? Also, would `npm shrinkwrap` solve this?

**Comment by krzysiek1507** [comment]
@jshumakerpruitt `es6-promise` >= 3.3.0 is the problem

**Comment by krzysiek1507** [comment]
@jshumakerpruitt @chrisdobler could you please take a look at #71?

**Comment by jshumakerpruitt** [comment]
@krzysiek1507 Awesome, I'll take a look at that PR tomorrow.

**Comment by jshumakerpruitt** [comment]
Just re-cloned the repo, and it worked perfectly.  Thanks!
